
--
--

-- MODIFICATIONS
-- - All Id are TablenameId
-- - location where reversed lol

DROP TABLE "Customer";
DROP TABLE "Supplier";
DROP TABLE "Invoice";
DROP TABLE "ProductCategory";
DROP TABLE "Product";
DROP TABLE "ProductLocation";
DROP TABLE "ItemStock";
DROP TABLE "OrderProduct";
DROP TABLE "Order";
DROP TABLE "Employee";
DROP TABLE "Role";

DROP TABLE "Warehouse";
DROP TABLE "WarehouseSections";

DROP TABLE "Island";
DROP TABLE "IslandPosition";

DROP TABLE "AisleSection";
DROP TABLE "AisleSectionPosition";
DROP TABLE "Aisle";
DROP TABLE "StraightLine";

DROP TABLE "BinStorage";
DROP TABLE "Bin";

DROP TABLE "InventoryMovement";


--
--
-- 

    

-- Roles Table
CREATE TABLE "Role" (
    "RoleId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "User" BOOLEAN NOT NULL,
    "Manager" BOOLEAN NOT NULL,
    "Admin" BOOLEAN NOT NULL
);

-- Employees Table
CREATE TABLE "Employee" (
    "EmployeeId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "Username" VARCHAR(255) NOT NULL,
    "RoleId" INTEGER REFERENCES "Role"("RoleId")
);

-- Warehouse Table
CREATE TABLE "Warehouse" (
    "WarehouseId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "WarehouseName" VARCHAR(255),
    "Address" VARCHAR(255) NOT NULL,
    "State" VARCHAR(255) NOT NULL,
    "Country" VARCHAR(255) NOT NULL,
    "ZipCode" INTEGER NOT NULL,
    "OwnerName" VARCHAR(255),
    "Phone" VARCHAR(255) NOT NULL,
    "Email" VARCHAR(255) NOT NULL
);

-- Warehouse Sections
CREATE TABLE "WarehouseSections" (
    "WarehouseSectionsId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "WarehouseId" INTEGER REFERENCES "Warehouse"("WarehouseId"),
    "Desc" VARCHAR(255)
);

-- Islands
CREATE TABLE "Island" (
  "IslandId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "WarehouseSectionsId" INTEGER REFERENCES "WarehouseSections"("WarehouseSectionsId")
);

-- Island Positions
CREATE TABLE "IslandPosition" (
    "IslandPositionId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "IslandId" INTEGER REFERENCES "Island"("IslandId"),
    "IslandCapacity" DECIMAL,
    "Heigh" DECIMAL,
    "Width" DECIMAL,
    "Length" DECIMAL
);


-- Straight Line
CREATE TABLE "StraightLine" (
    "SlId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "WarehouseSectionsId" INTEGER REFERENCES "WarehouseSections"("WarehouseSectionsId")
);

-- Aisles
CREATE TABLE "Aisle" (
    "AisleId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "SlId" INTEGER REFERENCES "StraightLine"("SlId"),
    "AisleName" VARCHAR(255)
);
-- Aisle Section
CREATE TABLE "AisleSection" (
    "AisleSectionId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "AisleId" INTEGER REFERENCES "Aisle"("AisleId"),
    "SectionName" VARCHAR(255)
);

-- Aisle Section Position
CREATE TABLE "AisleSectionPosition" (
        "PositionId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "AisleSectionId" INTEGER REFERENCES "AisleSection"("AisleSectionId"),
        "PositionDesc" VARCHAR(255),
        "PositionCapacity" DECIMAL,
        "Heigh" DECIMAL,
        "Width" DECIMAL,
        "Length" DECIMAL
);

-- Bin Storage
CREATE TABLE "BinStorage" (
  "BinSectionId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "WarehouseSectionsId" INTEGER REFERENCES "WarehouseSections"("WarehouseSectionsId"),
  "BinName" VARCHAR(255)
);
-- Bins
CREATE TABLE "Bin" (
    "BinId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "BinSectionId" INTEGER REFERENCES "BinStorage"("BinSectionId"),
    "BinCapacity" DECIMAL,
    "Heigh" DECIMAL,
    "Width" DECIMAL,
    "Length" DECIMAL
);

-- Customers
CREATE TABLE "Customer" (
    "CustomerId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "CustomerName" VARCHAR(255) NOT NULL,
    "Email" VARCHAR(255) NOT NULL,
    "Phone" VARCHAR(255) NOT NULL
);

-- Suppliers
CREATE TABLE "Supplier" (
    "SupplierId" INTEGER PRIMARY KEY,
    "SupplierName" VARCHAR(255) NOT NULL,
    "SupplierPhone" VARCHAR(255) NOT NULL,
    "SupplierEmail" VARCHAR(255) NOT NULL
);

-- Invoices
CREATE TABLE "Invoice" (
    "InvoiceId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" INTEGER REFERENCES "Customer"("CustomerId"),
    "SupplierId" INTEGER REFERENCES "Supplier"("SupplierId"),
    "Date" TIME NOT NULL,
    "Amount" DECIMAL,
    "Tax" DECIMAL,
    "TotalAmount" DECIMAL
);

-- Orders
CREATE TABLE "Order" (
    "OrderId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "InvoiceId" INTEGER REFERENCES "Invoice"("InvoiceId"),
    "EmployeeId" INTEGER REFERENCES "Employee"("EmployeeId"),
    "OrderStartDate" TIME NOT NULL,
    "OrderDueDate" TIME NOT NULL
);

-- Product Category
CREATE TABLE "ProductCategory" (
    "CategoryId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "CategoryName" VARCHAR(255),
    "CategoryDesc" VARCHAR(255)
);

-- Product
CREATE TABLE "Product" (
    "ProductId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "CategoryId" INTEGER REFERENCES "ProductCategory"("CategoryId"),
    "SKU" VARCHAR(255),
    "Name" VARCHAR(255),
    "Desc" VARCHAR(255),
    "Price" DECIMAL
);

-- Product Location
CREATE TABLE "ProductLocation" (
    "ProductLocationId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "IslandPositionId" INTEGER REFERENCES "IslandPosition"("IslandPositionId"),
    "BinId" INTEGER REFERENCES "Bin"("BinId"),
    "PositionId" INTEGER REFERENCES "AisleSectionPosition"("PositionId")
);

-- Item Stock
CREATE TABLE "ItemStock" (
    "ItemStockId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "ProductLocationId" INTEGER REFERENCES "ProductLocation"("ProductLocationId"),
    "ProductId" INTEGER REFERENCES "Product"("ProductId"),
    "Quantity" INTEGER NOT NULL,
    "Status" VARCHAR(255) NOT NULL
);

-- Order Product
CREATE TABLE "OrderProduct" (
    "OrderProductId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" INTEGER REFERENCES "Order"("OrderId"),
    "ProductId" INTEGER REFERENCES "Product"("ProductId"),
    "Quantity" INTEGER NOT NULL
);

-- Inventory Movement
CREATE TABLE "InventoryMovement" (
    "InventoryMovementId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "ItemStockId" INTEGER REFERENCES "ItemStock"("ItemStockId"),
    "OrderProductId" INTEGER REFERENCES "OrderProduct"("OrderProductId"),
    "FromProductLocationId" INTEGER REFERENCES "ProductLocation"("ProductLocationId"),
    "ToProductLocationId" INTEGER REFERENCES "ProductLocation"("ProductLocationId"),
    "QuantityChange" INTEGER NOT NULL,
    "MovementDate" TIME NOT NULL,
    "MovementBy" INTEGER REFERENCES "Employee"("EmployeeId")
);

